### ISSUE TITLE
ingredients/notifications not found

### ISSUE THREAD

**Issue by BadChoice** [devfake/laravel-elixir-spritesmith#1]
Got this error with last Laravel,

Error: Cannot find module 'laravel-elixir/ingredients/helpers/Notification'

I guess it is because they changed its location as they point there:

https://github.com/rynocouse/laravel-elixir-compass/issues/8

**Comment by BadChoice** [comment]
Just replace it:

Notification = require('laravel-elixir/ingredients/commands/Notification'),

**Comment by devinfd** [comment]
thanks for identifying the fix for this

**Comment by devfake** [comment]
great, thank you :)
