### ISSUE TITLE
positioning incorectly

### ISSUE THREAD

**Issue by devinfd** [devfake/laravel-elixir-spritesmith#5]
I honestly don't know which package (laravel-elixir-spritesmith, gulp.spritesmith, spritesmith) is causing the issue but I am suddenly having an issue where the positioning of the sprite background is all wrong. I've cleared the cache on my browser so its not that issue. Are you aware of any issues?

**Comment by devfake** [comment]
I tried it, and it works fine. Have you deleted your sprite.css and all your images, and start from scratch (maybe with other test images)?

**Comment by devinfd** [comment]
Yea I tried that and it cleared up. Thanks. I guess it was just having a bad day

Devin Dombrowski
dddesigns3@gmail.com
